config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts, only: [:new, :create]

  resources :stocks do
    collection do
      get 'edit_stocks'
      post 'save_edited_stocks'
      get 'stock_detail/:id', to: 'stocks#stock_detail', as: 'stock_detail'
    end
  
    member do
      get 'edit_individual', to: 'stocks#edit', as: 'edit_individual'
      patch '/', to: 'stocks#update'
    end

    resources :financial_reports, only: [:new, :create, :show, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/financial_report.rb
class FinancialReport < ApplicationRecord
  belongs_to :stock
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :financial_reports
  # Association
  belongs_to :user

  # Validation
  validates :user_id, presence: true
  validates :ticker_symbol, presence: true, uniqueness: { scope: :user_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  private

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/financial_reports_controller.rb
class FinancialReportsController < ApplicationController
  before_action :set_stock, only: [:new, :create, :show, :edit, :update]
  before_action :set_financial_report, only: [:show, :edit, :update]
  
  helper_method :estimate_vs_actual


  def new
    @financial_report = @stock.financial_reports.build
  end
  
  def create
    @financial_report = @stock.financial_reports.build(financial_report_params)
    if @financial_report.save
      redirect_to stock_financial_report_path(@stock, @financial_report)
    else
      render :new
    end
  end



  def show
  end
  
  
  def edit
  end

  def update
    if @financial_report.update(financial_report_params)
      redirect_to stock_financial_report_path(@stock, @financial_report), notice: 'Financial report was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_stock
    @stock = Stock.find(params[:stock_id])
  end

  def set_financial_report
    @financial_report = @stock.financial_reports.find(params[:id])
  end

  def estimate_vs_actual(estimate, actual)
    estimate == actual ? "Match" : "Mismatch"
  end
  
  def financial_report_params
    params.require(:financial_report).permit(:eps_estimate, :eps_actual, :revenue_estimate, :revenue_actual, :eps_guidance_estimate, :eps_guidance_actual, :revenue_guidance_estimate, :revenue_guidance_actual)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    render :new
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user! # ユーザーがログインしていることを確認する

  def index
    @stocks = current_user.stocks
  end

  def create
    params[:stocks].values.each do |ticker_symbol|
      next if ticker_symbol.blank? # Skip if ticker_symbol is blank
  
      stock = current_user.stocks.new(ticker_symbol: ticker_symbol)
      
      if stock.save
        puts "Successfully created stock with ticker_symbol: #{ticker_symbol}"
      else
        puts "Failed to create stock with ticker_symbol: #{ticker_symbol}. Errors: #{stock.errors.full_messages.join(', ')}"
      end
    end
  
    redirect_to stocks_path
  end
  
  def edit_stocks
    @stocks = current_user.stocks
  end
  
  def show
    @stock = Stock.find(params[:stock_id])
    @financial_report = @stock.financial_reports.find(params[:id])
  end
  
  def save_edited_stocks
  end

  def edit
    @stock = current_user.stocks.find(params[:id])
  end
  
  def update
    @stock = current_user.stocks.find(params[:id])
    if @stock.update(stock_params)
      redirect_to edit_stocks_stocks_path, notice: 'ティッカーシンボルを更新しました。'
    else
      render :edit
    end
  end
  
  private
  
  def stock_params
    params.require(:stock).permit(:ticker_symbol)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/financial_reports_helper.rb
module FinancialReportsHelper
end

app/helpers/laravel_mix_helper.rb
module LaravelMixHelper
  class LaravelMixError < StandardError; end
  MANIFEST_FILE = 'public/mix-manifest.json'

  def mix(path)
    unless File.exist?(MANIFEST_FILE)
      raise LaravelMixError, "The Mix manifest does not exist at #{MANIFEST_FILE}. Run `yarn run dev`."
    end

    manifest = JSON.parse(File.read(MANIFEST_FILE))
    asset_path(manifest.fetch(path) { raise LaravelMixError, "No asset found for #{path} in the Mix manifest." })
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/financial_reports/edit.html.erb
<h1>Edit Financial Report for <%= @stock.ticker_symbol %></h1>

<%= form_with(model: [@stock, @financial_report]) do |f| %>
  <div class="financial-report">
    <label>Year:</label> <%= f.text_field :year %>

    <label>Quarter:</label>
    <%= f.select :quarter, options_for_select([['Q1', 1], ['Q2', 2], ['Q3', 3], ['Q4', 4]], @financial_report.quarter) %>

    <table>
      <tr>
        <td></td>
        <td>Estimate</td>
        <td>Actual</td>
      </tr>
      <tr>
        <td>EPS</td>
        <td><%= f.text_field :eps_estimate %></td>
        <td><%= f.text_field :eps_actual %></td>
      </tr>
      <tr>
        <td>Revenue</td>
        <td><%= f.text_field :revenue_estimate %></td>
        <td><%= f.text_field :revenue_actual %></td>
      </tr>
      <tr>
        <td>Guidance (EPS)</td>
        <td><%= f.text_field :eps_guidance_estimate %></td>
        <td><%= f.text_field :eps_guidance_actual %></td>
      </tr>
      <tr>
        <td>Guidance (Revenue)</td>
        <td><%= f.text_field :revenue_guidance_estimate %></td>
        <td><%= f.text_field :revenue_guidance_actual %></td>
      </tr>
    </table>

    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/financial_reports/new.html.erb
<h1><%= @stock.ticker_symbol %> - New Financial Report</h1>

<%= form_with model: [@stock, @financial_report], url: stock_financial_reports_path(@stock), method: :post, local: true do |f| %>
  <div class="financial-report">
    <label>Year:</label> <%= f.number_field :year %>
    <label>Quarter:</label>
    <%= f.select :quarter, options_for_select([['Q1', 1], ['Q2', 2], ['Q3', 3], ['Q4', 4]]) %>

    <table>
      <tr>
        <td></td>
        <td>Estimate</td>
        <td>Actual</td>
      </tr>
      <tr>
        <td>EPS</td>
        <td><%= f.text_field :eps_estimate %></td>
        <td><%= f.text_field :eps_actual %></td>
      </tr>
      <tr>
        <td>Revenue</td>
        <td><%= f.text_field :revenue_estimate %></td>
        <td><%= f.text_field :revenue_actual %></td>
      </tr>
      <tr>
        <td>Guidance (EPS)</td>
        <td><%= f.text_field :eps_guidance_estimate %></td>
        <td><%= f.text_field :eps_guidance_actual %></td>
      </tr>
      <tr>
        <td>Guidance (Revenue)</td>
        <td><%= f.text_field :revenue_guidance_estimate %></td>
        <td><%= f.text_field :revenue_guidance_actual %></td>
      </tr>
    </table>
  </div>

  <div>
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/financial_reports/show.html.erb
<h1><%= @stock.ticker_symbol %></h1>

<div class="financial-report">
  <label>Year:</label> <%= @financial_report.year %>
  <label>Quarter:</label>
  <%= select_tag :quarter, options_for_select([['Q1', 1], ['Q2', 2], ['Q3', 3], ['Q4', 4]], @financial_report.quarter) %>

  <table>
    <tr>
      <td></td>
      <td>Estimate</td>
      <td>Actual</td>
      <td>Result</td>
    </tr>
    <tr>
      <td>EPS</td>
      <td><%= @financial_report.eps_estimate %></td>
      <td><%= @financial_report.eps_actual %></td>
      <td><%= estimate_vs_actual(@financial_report.eps_estimate, @financial_report.eps_actual) %></td>
    </tr>
    <tr>
      <td>Revenue</td>
      <td><%= @financial_report.revenue_estimate %></td>
      <td><%= @financial_report.revenue_actual %></td>
      <td><%= estimate_vs_actual(@financial_report.revenue_estimate, @financial_report.revenue_actual) %></td>
    </tr>
    <tr>
      <td>Guidance (EPS)</td>
      <td><%= @financial_report.eps_guidance_estimate %></td>
      <td><%= @financial_report.eps_guidance_actual %></td>
      <td><%= estimate_vs_actual(@financial_report.eps_guidance_estimate, @financial_report.eps_guidance_actual) %></td>
    </tr>
    <tr>
      <td>Guidance (Revenue)</td>
      <td><%= @financial_report.revenue_guidance_estimate %></td>
      <td><%= @financial_report.revenue_guidance_actual %></td>
      <td><%= estimate_vs_actual(@financial_report.revenue_guidance_estimate, @financial_report.revenue_guidance_actual) %></td>
    </tr>
  </table>
</div>

<div>
  <%= link_to 'Edit', edit_stock_financial_report_path(@stock, @financial_report), class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- titleを変更します -->
    <title>Investment Insight</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Style追加 -->
    <link rel="stylesheet" href="<%= mix('/css/app.css') %>">
    <!-- Javascript -->
    <script src="<%= mix('/js/bootstrap.js') %>"></script>
  </head>

  <body>
    <div class="main-container">
    <!--  ナビゲーションバー -->
      <nav class="custom-navbar">
        <div id="menuToggle">
          <input type="checkbox" />
          <span></span>
          <span></span>
          <span></span>
          <ul id="menu">
            <% if user_signed_in? %>
              <!-- ログインしている場合に表示されます -->
              <!-- user_signed_in? は device が提供している認証済みかを判定するメソッドです -->
              <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
              <li>
                <%= link_to "保有銘柄", "/stocks", class: "nav-link" %>
              </li>
              <li>
                <%= link_to "銘柄追加", new_post_path, class: "nav-link" %>
              </li>
            <% else %>
              <!-- ログインしていない場合に表示されます -->
              <!-- else 以降は前述のif文の否定になります -->
              <li>
                <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
              </li>
              <li>
                <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
      <% end %>
  
      <div class="bg-white text-dark">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/new.html.erb
<div class="container">
   <h2>Earnings Surprise</h2>
</div>

app/views/stocks/edit.html.erb
<%= form_with(model: @stock, url: stock_path(@stock), method: :patch) do |f| %>
  <div>
    <%= f.label :ticker_symbol, "ティッカーシンボル" %>
    <%= f.text_field :ticker_symbol %>
  </div>
  <div>
    <%= f.submit "更新" %>
  </div>
<% end %>

app/views/stocks/edit_stocks.html.erb
<%= form_with url: save_edited_stocks_stocks_path do |f| %>
  <table>
    <% @stocks.each_with_index do |stock, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= text_field_tag "stock[#{index}][ticker_symbol]", stock.ticker_symbol, placeholder: '-', size: 4 %></td>
        
        <td>
          <% if stock.financial_reports.any? %>
            <%= link_to 'detail', stock_financial_report_path(stock, stock.financial_reports.last) %>
          <% else %>
            <%= link_to 'No reports available', new_stock_financial_report_path(stock) %>
          <% end %>
        </td>
        
        <td><%= link_to 'edit', edit_individual_stock_path(stock) %></td>
        <td><button type="button" onclick="deleteStock(this)">delete</button></td>
      </tr>
    <% end %>
    <% (15 - @stocks.count).times do |i| %>
      <tr>
        <td><%= i + @stocks.count + 1 %></td>
        <td><%= text_field_tag "stock[#{i + @stocks.count}][ticker_symbol]", '', placeholder: '-', size: 4, disabled: true %></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    <% end %>
  </table>
  <%= f.submit "SAVE" %>
<% end %>

app/views/stocks/index.html.erb
<div class="container">
  <h1>Your Stocks</h1>
  
  <% @stocks.each do |stock| %>
    <div class="ticker-symbol">
      <%= stock.ticker_symbol %> <!-- この部分を更新 -->
    </div>
  <% end %>
  <%= link_to 'edit', edit_stocks_stocks_path, class: 'btn btn-primary' %>
</div>